set(CMAKE_OSX_SYSROOT macosx CACHE STRING "macOS SDK" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET 26.0 CACHE STRING "Metal 4 minimum macOS version" FORCE)
set(CMAKE_OSX_ARCHITECTURES arm64 CACHE STRING "Apple Silicon" FORCE)
foreach(language C CXX OBJCXX)
    if(language STREQUAL "C")
        set(compiler clang)
    else()
        set(compiler clang++)
    endif()
    set(CMAKE_${language}_COMPILER "/opt/homebrew/opt/llvm/bin/${compiler}" CACHE FILEPATH "Homebrew LLVM compiler" FORCE)
endforeach()
